import logging
from pathlib import Path
from typing import Optional

import pandas as pd

from src.formatter.factory_csv_formatter import FactoryCSVFormatter
from src.cleaners.ASICS_cleaner import ASICSCleaner

logger = logging.getLogger(__name__)


class ASICSFormatter(FactoryCSVFormatter):
    """Formatter for CSV files generated by ASICS.

    ASICS format: rows are metabolites, columns are experiments.
    """

    def format(self, df: pd.DataFrame) -> pd.DataFrame:
        """Formats an ASICS DataFrame into the project's standardized schema.
        """
        # If it's in Long format, pivot it to Wide
        if 'Experiment' in df.columns and 'Metabolite' in df.columns:
            logger.info("Pivoting ASICS Long format to Wide...")
            df = df.pivot(
                index='Metabolite', 
                columns='Experiment', 
                values='Concentration_uM_Final'
            ).fillna(0.0)
            df.index.name = "metabolite"
            
        return df
