import logging
from pathlib import Path
from typing import Optional

import pandas as pd

from src.formatter.factory_csv_formatter import FactoryCSVFormatter

logger = logging.getLogger(__name__)


class ASICSFormatter(FactoryCSVFormatter):
    """Formatter for CSV files generated by ASICS.

    ASICS format: rows are metabolites, columns are experiments.
    """

    def format(self, file_path: str) -> Optional[str]:
        """Formats an ASICS CSV into the project's standardized schema.

        Args:
            file_path: Path to the ASICS CSV file.

        Returns:
            Path to the formatted output file, or None on failure.
        """
        try:
            df: pd.DataFrame = self.reader.read(file_path, index_col=0)

            # Clean experiment names (columns) and metabolite names (index)
            df.columns = [str(col).replace('"', '').strip() for col in df.columns]
            df.index = [str(idx).replace('"', '').strip() for idx in df.index]
            df.index.name = "metabolite"

            output_path: Path = self.output_dir / f"formatted_{Path(file_path).name}"
            df.to_csv(output_path)
            logger.info(f"Formatted ASICS file saved to: {output_path}")
            return str(output_path)
        except Exception as e:
            logger.error(f"Error processing ASICS file '{file_path}': {e}")
            return None
