import logging
from pathlib import Path
from typing import Optional

import pandas as pd

from src.formatter.factory_csv_formatter import FactoryCSVFormatter

logger = logging.getLogger(__name__)


class MagMetFormatter(FactoryCSVFormatter):
    """Formatter for CSV files generated by MagMet.

    Skips metadata rows, removes the 'HMDB ID' column, and
    strips the '.fid' suffix from experiment names.
    """

    def format(self, file_path: str) -> Optional[str]:
        """Formats a MagMet CSV into the project's standardized schema.

        Args:
            file_path: Path to the MagMet CSV file.

        Returns:
            Path to the formatted output file, or None on failure.
        """
        try:
            # Locate real header row (EAFP: open and scan for marker)
            header_idx: int = self._find_header_index(file_path)
            df: pd.DataFrame = self.reader.read(file_path, skiprows=header_idx)

            # Drop HMDB ID column if present
            if "HMDB ID" in df.columns:
                df = df.drop(columns=["HMDB ID"])

            # Set 'Compound Name' as index
            if "Compound Name" in df.columns:
                df = df.set_index("Compound Name")
                df.index.name = "metabolite"

            # Strip .fid suffix from column names (experiment names)
            df.columns = [str(col).replace(".fid", "").strip() for col in df.columns]

            # Standardize missing values and enforce numeric dtype
            df = df.fillna(0).replace("", 0)
            df = df.apply(pd.to_numeric, errors="coerce").fillna(0)

            output_path: Path = self.output_dir / f"formatted_{Path(file_path).name}"
            df.to_csv(output_path)
            logger.info(f"Formatted MagMet file saved to: {output_path}")
            return str(output_path)
        except Exception as e:
            logger.error(f"Error processing MagMet file '{file_path}': {e}")
            return None

    @staticmethod
    def _find_header_index(file_path: str) -> int:
        """Finds the index of the line containing the 'HMDB ID' header.

        Args:
            file_path: Path to the MagMet CSV file.

        Returns:
            Zero-based index of the header line.
        """
        with open(file_path, "r") as f:
            for idx, line in enumerate(f):
                if line.startswith("HMDB ID"):
                    return idx
        return 0
