import logging
from pathlib import Path
from typing import Optional

import pandas as pd

from src.formatter.factory_csv_formatter import FactoryCSVFormatter
from src.cleaners.MagMet_cleaner import MagMetCleaner

logger = logging.getLogger(__name__)


class MagMetFormatter(FactoryCSVFormatter):
    """Formatter for CSV files generated by MagMet.

    Uses MagMetCleaner for content standardization.
    """

    def format(self, df: pd.DataFrame) -> pd.DataFrame:
        """Formats a MagMet DataFrame into the project's standardized schema.

        Args:
            df: The cleaned MagMet DataFrame.

        Returns:
            The formatted DataFrame.
        """
        # Data is already correctly formatted by the cleaner
        return df
