import logging
from pathlib import Path
from typing import Optional

import pandas as pd

from src.formatter.factory_csv_formatter import FactoryCSVFormatter
from src.cleaners.MagMet_cleaner import MagMetCleaner

logger = logging.getLogger(__name__)


class MagMetFormatter(FactoryCSVFormatter):
    """Formatter for CSV files generated by MagMet.

    Skips metadata rows and uses MagMetCleaner for content standardization.
    """

    def __init__(self, output_dir: str = "data/processed/formatted") -> None:
        super().__init__(output_dir, cleaner=MagMetCleaner())

    def format(self, file_path: str) -> Optional[str]:
        """Formats a MagMet CSV into the project's standardized schema.

        Args:
            file_path: Path to the MagMet CSV file.

        Returns:
            Path to the formatted output file, or None on failure.
        """
        try:
            # 1. Locate real header row and Read
            header_idx: int = self._find_header_index(file_path)
            df: pd.DataFrame = self.reader.read(file_path, skiprows=header_idx)

            # 2. Clean (using the injected cleaner)
            if self.cleaner:
                df = self.cleaner.clean(df)

            # 3. Save
            output_path: Path = self.output_dir / f"formatted_{Path(file_path).name}"
            df.to_csv(output_path)
            logger.info(f"Formatted MagMet file saved to: {output_path}")
            return str(output_path)

        except Exception as e:
            logger.error(f"Error processing MagMet file '{file_path}': {e}")
            return None

    @staticmethod
    def _find_header_index(file_path: str) -> int:
        """Finds the index of the line containing the 'HMDB ID' header.

        Args:
            file_path: Path to the MagMet CSV file.

        Returns:
            Zero-based index of the header line.
        """
        with open(file_path, "r") as f:
            for idx, line in enumerate(f):
                if line.startswith("HMDB ID"):
                    return idx
        return 0
