import logging
from pathlib import Path
from typing import Optional

import pandas as pd

from src.formatter.factory_csv_formatter import FactoryCSVFormatter
from src.cleaners.nmRanalysis_cleaner import NmRanalysisCleaner

logger = logging.getLogger(__name__)


class NmRanalysisFormatter(FactoryCSVFormatter):
    """Formatter for CSV files generated by nmRanalysis.

    Pivots cleaned data to the standard format:
    rows = metabolites, columns = samples.
    """

    def format(self, df: pd.DataFrame) -> pd.DataFrame:
        """Formats an nmRanalysis DataFrame into the project's standardized schema.

        Args:
            df: The cleaned nmRanalysis DataFrame.

        Returns:
            The pivoted DataFrame.
        """
        # Format (Pivot)
        pivot_df: pd.DataFrame = df.pivot(
            index="Base_Metabolite", columns="Sample", values="Quantity"
        ).fillna(0.0)
        pivot_df.index.name = "metabolite"
        
        return pivot_df