import logging
from pathlib import Path
from typing import Optional

import pandas as pd

from src.formatter.factory_csv_formatter import FactoryCSVFormatter

logger = logging.getLogger(__name__)


class NmRanalysisFormatter(FactoryCSVFormatter):
    """Formatter for CSV files generated by nmRanalysis.

    For each (Sample, Metabolite) pair, selects the quantification with
    the lowest 'Fitting Error'. The result is pivoted to the standard
    format: rows = metabolites, columns = samples.
    """

    _REQUIRED_COLS: list[str] = ["Sample", "Metabolite", "Quantity", "Fitting Error"]

    def format(self, file_path: str) -> Optional[str]:
        """Formats an nmRanalysis CSV into the project's standardized schema.

        Args:
            file_path: Path to the nmRanalysis CSV file.

        Returns:
            Path to the formatted output file, or None on failure.
        """
        try:
            # Read CSV handling comma as thousands separator
            df: pd.DataFrame = self.reader.read(file_path, thousands=",")

            # Validate required columns
            missing: list[str] = [c for c in self._REQUIRED_COLS if c not in df.columns]
            if missing:
                raise ValueError(f"Missing required columns: {missing}")

            # Extract base metabolite name by removing trailing " [number]" suffix
            df["Base_Metabolite"] = df["Metabolite"].str.replace(
                r"\s+\[\d+\]$", "", regex=True
            )

            # Coerce numeric types for key columns
            df["Fitting Error"] = pd.to_numeric(df["Fitting Error"], errors="coerce")
            df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce")

            # Select the row with the lowest Fitting Error per (Sample, Metabolite)
            best_idx: pd.Index = df.groupby(["Sample", "Base_Metabolite"])["Fitting Error"].idxmin()
            best_fits: pd.DataFrame = df.loc[best_idx].copy()

            # Remove 'X' prefix automatically added by nmRanalysis to numeric sample names
            best_fits["Sample"] = best_fits["Sample"].astype(str).str.replace(r"^X", "", regex=True)

            # Pivot to standard format: rows = metabolite, columns = sample
            pivot_df: pd.DataFrame = best_fits.pivot(
                index="Base_Metabolite", columns="Sample", values="Quantity"
            ).fillna(0.0)
            pivot_df.index.name = "metabolite"

            output_path: Path = self.output_dir / f"formatted_{Path(file_path).name}"
            pivot_df.to_csv(output_path)
            logger.info(f"Formatted nmRanalysis file saved to: {output_path}")
            return str(output_path)

        except Exception as e:
            logger.error(f"Error processing nmRanalysis file '{file_path}': {e}")
            return None