-- Migration: Adicionar colunas precisao e recall nas tabelas de análise estatística

ALTER TABLE analise_espectro
ADD COLUMN IF NOT EXISTS precisao DOUBLE PRECISION DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS recall DOUBLE PRECISION DEFAULT 0.0;

ALTER TABLE analise_metabolito
ADD COLUMN IF NOT EXISTS precisao DOUBLE PRECISION DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS recall DOUBLE PRECISION DEFAULT 0.0;

ALTER TABLE analise_ferramenta
ADD COLUMN IF NOT EXISTS precisao DOUBLE PRECISION DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS recall DOUBLE PRECISION DEFAULT 0.0;
